import { Link, createFileRoute } from "@tanstack/react-router";
import { BotMessageSquare, ListChecks, Mail, NotebookPen, Search } from "lucide-react";

import { AppLayout } from "@/components/AppLayout";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "WorkFlow AI — AI workplace productivity assistant" },
      {
        name: "description",
        content:
          "WorkFlow AI is a student-built assistant for writing emails, summarising meeting notes, planning tasks, researching topics and chatting about workplace productivity.",
      },
      { property: "og:title", content: "WorkFlow AI — AI workplace productivity assistant" },
      {
        property: "og:description",
        content: "Email generator, meeting summarizer, task planner, research assistant and workplace chatbot in one app.",
      },
    ],
  }),
  component: Dashboard,
});

const FEATURES = [
  {
    to: "/email",
    icon: Mail,
    title: "Email Generator",
    text: "Turn a recipient, purpose and key points into an editable professional email.",
  },
  {
    to: "/meetings",
    icon: NotebookPen,
    title: "Meeting Summarizer",
    text: "Paste raw notes and get a summary, decisions, action items and deadlines.",
  },
  {
    to: "/tasks",
    icon: ListChecks,
    title: "Task Planner",
    text: "Add tasks with deadlines and priorities, then ask the AI for a suggested order.",
  },
  {
    to: "/research",
    icon: Search,
    title: "Research Assistant",
    text: "Get a structured starting point on a topic, without invented sources.",
  },
  {
    to: "/chat",
    icon: BotMessageSquare,
    title: "Workplace Chatbot",
    text: "Ask questions about communication, planning and productivity.",
  },
] as const;

function Dashboard() {
  return (
    <AppLayout
      title="Welcome to WorkFlow AI"
      description="An AI-powered workplace productivity assistant."
    >
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {FEATURES.map(({ to, icon: Icon, title, text }) => (
          <Link
            key={to}
            to={to}
            className="group rounded-xl border bg-card p-5 transition-colors hover:border-primary/50 hover:bg-secondary"
          >
            <span className="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Icon className="h-5 w-5" aria-hidden />
            </span>
            <h2 className="mt-4 text-base font-semibold">{title}</h2>
            <p className="mt-1 text-sm text-muted-foreground">{text}</p>
          </Link>
        ))}
      </div>

      <section className="mt-8 rounded-xl border border-accent/40 bg-accent/10 p-5">
        <h2 className="text-base font-semibold">Before you start</h2>
        <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
          <li>• All output on this site is generated by AI and may contain errors — verify anything important.</li>
          <li>• Do not paste confidential or personal information into the forms.</li>
          <li>• Your tasks, settings and chat stay in this browser only; nothing is stored on a server.</li>
        </ul>
        <Link to="/responsible-ai" className="mt-3 inline-block text-sm font-medium text-primary underline">
          Read the Responsible AI notes
        </Link>
      </section>
    </AppLayout>
  );
}
